<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getPackageNameOfService</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
Zwluc05hbWUgICAgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgIm5zTmFt
ZSIgKTsNClN0cmluZyAgZGVmYXVsdFBOID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJkZWZhdWx0IiApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQppZiAoIGRl
ZmF1bHRQTiA9PSBudWxsICkgDQoJZGVmYXVsdFBOID0gInVua25vd24iOw0KU3RyaW5nICAgICAg
IGJhY2sgPSBkZWZhdWx0UE47DQoNCmlmICggbnNOYW1lICE9IG51bGwgJiYgbnNOYW1lLmxlbmd0
aCgpID4gMCApIHsNCgl0cnkgew0KCU5TU2VydmljZSAgc2VydmljZSA9IChOU1NlcnZpY2UpIE5h
bWVzcGFjZS5jdXJyZW50KCkuZ2V0Tm9kZSggbnNOYW1lICk7DQoJYmFjayAgICAgICAgICAgICAg
ID0gc2VydmljZS5nZXRQYWNrYWdlKCkuZ2V0TmFtZSgpOw0KCX0NCgljYXRjaCAoVGhyb3dhYmxl
IGUpIHsNCgkJLy9TdXBwcmVzcyBleGNlcHRpb24NCgl9DQp9DQpwaXBlbGluZUN1cnNvciA9IHBp
cGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgInBhY2th
Z2VOYW1lIiwgYmFjayApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KCQ==</value>
</Values>
