{
 "title": "webMethods - Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "getStage", "label": "Environment", "query": { "query": "label_values(stage)" } },
   { "name": "getPackage", "label": "Package", "query": { "query": "label_values(package)" } }
  ]
 },
 "panels": [
  { "title": "$getStage || wM Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "getStage" },
  {
   "title": "$getStage || wM Services",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{stage=\"$getStage\"}",
     "legendFormat": "{{wm}}"
    }
   ]
  },
  {
   "title": "$getStage || wM Service CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{stage=\"$getStage\"}[1m])",
     "legendFormat": "{{wm}}"
    },
    {
     "expr": "rate(sag_is_process_cpu_seconds_total{stage=\"$getStage\"}[1m])",
     "legendFormat": "{{wm}}"
    }
   ]
  },
  {
   "title": "$getStage || wM Services  Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sag_is_serverheap_used{stage=\"$getStage\"} / sag_is_serverheap_max{stage=\"$getStage\"}",
     "legendFormat": "{{wm}}"
    },
    {
     "expr": "jvm_memory_bytes_used{stage=\"$getStage\", area=\"heap\"} / jvm_memory_bytes_max{stage=\"$getStage\", area=\"heap\"}",
     "legendFormat": "{{wm}}"
    }
   ]
  },
  {
   "title": "$getStage || IS Package Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "getStage",
   "collapsed": true,
   "panels": [
    {
     "title": "$getStage || $getPackage ",
     "type": "status-history",
     "description": "Adapter Connection, Listener, Notification, Trigger, Scheduler Tasks and failed Processes",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
     "repeat": "getPackage",
     "targets": [
      {
       "expr": "sag_is_adapter_connection_state{stage=\"$getStage\", package=~\"$getPackage\"}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sag_is_adapter_listener_state{stage=\"$getStage\", package=~\"$getPackage\"}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sag_is_adapter_notification_state{stage=\"$getStage\", package=\"$getPackage\"}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "100 + (sag_is_umtrigger_state{stage=\"$getStage\", package=\"$getPackage\"} * 10 ) + (sag_is_umtrigger_processingstate{stage=\"$getStage\", package=\"$getPackage\"} * 1)  ",
       "legendFormat": "{{triggerName}}"
      },
      {
       "expr": "1000 + (sag_is_scheduler_status{stage=\"$getStage\", package=\"$getPackage\"} * 10 ) + (sag_is_scheduler_hasfailed{stage=\"$getStage\", package=\"$getPackage\"} * 1)  ",
       "legendFormat": "{{schedulername}}"
      },
      {
       "expr": "(rate(sag_pe_processes_failed{stage=\"$getStage\",package=\"$getPackage\"}[1m])*100000)+10000",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$getStage || IS JDBC Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "getStage",
   "collapsed": true,
   "panels": [
    {
     "title": "$getStage || IS JDBC Pools Connection Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sag_is_jdbcpool_connections_pooled{stage=\"$getStage\"} / sag_is_jdbcpool_connections_max {stage=\"$getStage\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "$getStage || IS JDBC Pool fail-fast mode",
     "type": "status-history",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sag_is_jdbcpool_connections_is_in_fail_fast_mode {stage=\"$getStage\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$getStage || IS Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "getStage",
   "collapsed": true,
   "panels": [
    {
     "title": "$getStage || IS Running Services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "sag_is_services_running{stage=\"$getStage\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "$getStage || IS Thread CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "sag_is_thread_cpu_usage{stage=\"$getStage\"}",
       "legendFormat": "{{threadname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$getStage || IS -> UM Messaging Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "getStage",
   "collapsed": true,
   "panels": [
    {
     "title": "$getStage || Messaging Connection",
     "type": "status-history",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sag_is_jmsconnection_enabled{stage=\"$getStage\"}",
       "legendFormat": "{{ConnectionAliasName}}"
      },
      {
       "expr": "sag_is_umconnection_enabled{stage=\"$getStage\"}",
       "legendFormat": "{{ConnectionAliasName}}"
      }
     ]
    },
    {
     "title": "UM Pending Messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "sag_um_topic_durable_pending_total{stage=\"$getStage\"}",
       "legendFormat": "{{durable_name}}"
      },
      {
       "expr": "sag_um_queue_connection_pending_total{stage=\"$getStage\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "$getStage || BPM Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "getStage" },
  {
   "title": "Rate of Processes started, completed or failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(sag_pe_processes_completed{stage=\"$getStage\"}[1m])",
     "legendFormat": "completed: {{name}}"
    },
    {
     "expr": "rate(sag_pe_processes_failed{stage=\"$getStage\"}[1m])",
     "legendFormat": "failed: {{name}}"
    },
    {
     "expr": "rate(sag_pe_processes_started{stage=\"$getStage\"}[1m])",
     "legendFormat": "started: {{name}}"
    }
   ]
  },
  {
   "title": "Process Instance non activity time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(sag_pe_process_non_activity_duration_time{stage=\"$getStage\"}[1m])",
     "legendFormat": "{{model}}: {{name}}"
    }
   ]
  },
  { "title": "$getStage || Scheduler Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "getStage" },
  {
   "title": "$getStage || Scheduler Tasks Status",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sag_is_scheduler_hasfailed{package=~\"$getPackage\"} + (sag_is_scheduler_status{package=~\"$getPackage\"}*10)",
     "legendFormat": "{{schedulername}}"
    }
   ]
  },
  {
   "title": "$getStage || GWA Scheduler Tasks Status",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sag_is_scheduler_hasfailed{package=~\"EDA_GWA_Dunkelverarbeitung|EDA_GWA_Main\"} + (sag_is_scheduler_status{package=~\"EDA_GWA_Dunkelverarbeitung|EDA_GWA_Main\"}*10)",
     "legendFormat": "{{schedulername}}"
    }
   ]
  },
  {
   "title": "$getStage || LND Scheduler Tasks Status",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 42 },
   "targets": [
    {
     "expr": "sag_is_scheduler_status{stage=\"$getStage\", package=~\"EDA_LN_CHECK|EDA_LN_digital|EDA_SDD|EDA_SDD_DELTA\"}",
     "legendFormat": "{{schedulername}}"
    }
   ]
  }
 ]
}